webpage/bigproject/bigproject/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views, notice_views
import common.views as common_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('safe.urls')),
    path('board/',include('board.urls')), # 이거랑
    path('board/', base_views.index, name='index'), # 해결 필요 : 어째서 둘 다 해야 작동하지?
    path('common/',include('common.urls')),
    path('common/profile',common_views.profile_view, name='profile'),
    path('dash/',include('dash.urls')),
    path('emotion/', include(('emotion.urls', 'emotion'), namespace='emotion')),
    path('board/<int:notice_id>/download', notice_views.FileDownloadView.as_view(), name="download"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webpage/bigproject/board/urls.py
from django.urls import path
from .views import base_views, notice_views, reply_views

app_name = 'board'
urlpatterns=[
    #base_views
    path('', base_views.index, name='index'),
    path('<int:notice_id>/', base_views.detail, name='detail'),
    
    #notice_views
    path('notice/create/', notice_views.notice_create, name='notice_create'),
    #NoticeCreateView
    path('notice/modify/<int:notice_id>/', notice_views.notice_modify, name='notice_modify'),
    path('notice/delete/<int:notice_id>/', notice_views.notice_delete, name='notice_delete'),
    
    #reply_views
    path('notice/create/<int:notice_id>', reply_views.reply_create, name='reply_create'),
    path('reply/modify/<int:reply_id>/', reply_views.reply_modify, name='reply_modify'),
    path('reply/delete/<int:reply_id>/', reply_views.reply_delete, name='reply_delete'),
]

webpage/bigproject/dash/urls.py
from django.urls import path
from . import views

app_name = 'dash'
urlpatterns = [
    path('', views.mainboard, name='main'),
    path('<str:dist_id>', views.district, name='district'),
    path('alertalarm/',views.alertalarm, name='alertalarm'),
    path('company_table/<str:dist_id>', views.company_table, name='company_table'),
    path('alarm_table/<str:dist_id>', views.alarm_table, name='alarm_table'),
    path('accident_table/<str:dist_id>', views.accident_table, name='accident_table'),
    path('status_table/<str:dist_id>', views.status_table, name='status_table'),
    #path('acc_create/', views.acc_create, name='acc_create'),
]

webpage/bigproject/dash/models.py
from django.db import models

# Create your models here.

webpage/bigproject/dash/forms.py
from django import forms
from safe.models import Accident

class AccidentForm(forms.ModelForm):
    class Meta:
        model = Accident
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }

webpage/bigproject/dash/views.py
from django.shortcuts import render, HttpResponse
import folium
import json

from safe.models import Alarm, Accident
from common.models import Company, User, Group
from emotion.models import Emotion
from board.models import Reply,Notice
import datetime

from kiwipiepy import Kiwi

# Create your views here.
def mainboard(request):
    now = datetime.datetime.now()
    datas = {'data': []}
    dists = ['수정구','분당구','중원구']
    m_labels = []
    emo_list = []
    for dist_id in dists:
        company_list = Company.objects.filter(locate__exact=dist_id)
        group_list = Group.objects.filter(company_id__in=company_list)
        alarm_list = Alarm.objects.filter(group_id__in=group_list).order_by('-date')
        m_labels = []
        m_chart = []
        for i in range(15):
            m = now - datetime.timedelta(days=i)
            m_labels.append(m.strftime("%m월 %d일"))
            
            m_start = m.strftime("%Y-%m-%d 00:00:00")
            m_end = m.strftime("%Y-%m-%d 23:59:59")
            
            m_alarm = alarm_list.filter(date__range=[m_start, m_end]).count()
            m_chart.append(m_alarm)
        m_labels.reverse()
        m_chart.reverse()
        datas['data'].append([dist_id, m_chart])
        
        # 텍스트 AI - 감정
        num_of_users = 0
        for company in company_list:
            num_of_users += company.workers
        emos = Emotion.objects.filter(company_id__in=company_list)
        done = emos.count()
        if done == 0:
            percent = 0
        else:
            percent = int((emos.filter(feel__exact=True).count()/done)*100)
        emo_list.append({'workers':num_of_users, 'name':dist_id, 'done':done, 'percent':percent})
    datas['emo_list'] = emo_list
    datas['label'] = m_labels
    datas['dists'] = dists
    return render(request, 'dash/mainboard.html',datas)

# 실시간 알람 알림
def alertalarm(request):
    dist_id = request.user.address
    company_list = Company.objects.filter(locate__exact=dist_id)
    group_list = Group.objects.filter(company_id__in=company_list)
    temp = Alarm.objects.filter(group_id__in=group_list).order_by('-date')
    
    now = datetime.datetime.now()
    limit = now-datetime.timedelta(seconds=30) # 지금 시간 기준 30초(변경 가능) 내에 온 알림이 존재하면 팝업 띄움.
    start = limit.strftime("%Y-%m-%d %H:%M:%S")
    end = now.strftime("%Y-%m-%d %H:%M:%S")
    alarm = temp.filter(date__range=[start, end])
    
    if alarm:
        alarm = alarm[0]
        context = {'message': "알람이 도착했습니다! <br> 시간:" +str(alarm.date.time())+"<br> 그룹:"+str(alarm.group_id) }
    else:
        context = {'message': ""}
    return HttpResponse(json.dumps(context), content_type="application/json")


def district(request,dist_id):
    datas = {}
    datas['dist_id'] = dist_id
    
    # ==============  업체 별 현황 - 바 차트 & 근로자 긍부정   =============
    company_list = Company.objects.filter(locate__exact=dist_id)
    co_labels = []
    chart_company = []
    emo_list = []
    
    kiwi = Kiwi()
    kiwi.prepare()
    good_li = {}
    bad_li = {}
    not_use = ['많','거','중','오늘','것','어제','하','좋','힘들','모르',
               '사','개','들','남기','오']
    
    for company in company_list:
        num_of_users = company.workers
        co_labels.append(company.name)
        chart_company.append(num_of_users)
        
        # ============텍스트 AI - 감정
        emos = Emotion.objects.filter(company_id__exact=company.company_id)
        done = emos.count()
        if done == 0:
            percent = 0
        else:
            percent = int((emos.filter(feel__exact=True).count()/done)*100)
        emo_list.append({'workers':num_of_users, 'name':company.name, 'done':done, 'percent':percent})
        
        # ============단어 순위 [[진행중]] 
        for e in emos:
            token = kiwi.tokenize(e.text)
            for t in token:
                if t.tag in ('NNG','NNB','VV','VA') and (t.form not in not_use):
                    if e.feel : #긍정
                        if t.form not in good_li.keys():
                            good_li[t.form] = 0
                        good_li[t.form] += 1
                    else: # 부정
                        if t.form not in bad_li.keys():
                            bad_li[t.form] = 0
                        bad_li[t.form] += 1
    good_li = list(good_li.items())
    good_li.sort(key=lambda x:x[1], reverse=True)
    if len(good_li) > 10:
        good_li = good_li[:10]
        
    bad_li = list(bad_li.items())
    bad_li.sort(key=lambda x:x[1], reverse=True)
    if len(bad_li) > 10:
        bad_li = bad_li[:10]

    datas['good_li'] = good_li
    datas['bad_li'] = bad_li
    datas['emo_list'] = emo_list
    datas['co_labels'] = co_labels
    datas['chart_company'] = chart_company
    datas['company_list'] = company_list
    
    # ====================== map 그리기 ======================
    
    # 해당 구에 속해있는 그룹들
    group_list = Group.objects.filter(company_id__in=company_list)
    
    # 일시 기준 최신 순으로 모든 알람 정렬 
    # to-do : 일정 기간만 넣기 (현 시점으로는 데이터가 몇 개 없어서 전부로 진행함) [추후 수정]
    alarm_list = Alarm.objects.filter(group_id__in=group_list).order_by('-date')
    
    start = False
    #알람마다 마커 추가. GPS 값 없으면 표시되지 않음.
    for alarm in alarm_list:
        if alarm.latitude and alarm.latitude:
            la = alarm.latitude
            lo = alarm.longitude
            if start == False:
                # 제일 최근 알람 기준으로 맵 시작점 세팅
                m = folium.Map(location=[la, lo],zoom_start=14, height=400)
                folium.TileLayer('cartodbpositron').add_to(m)
                start = True
            pop = alarm.date # 마커 클릭 시 나타나는 팝업. 일단 알람 시각으로 지정함. [추후 수정]
            folium.Marker([la, lo], popup=pop, 
                    icon = (folium.Icon(icon= "info", prefix="fa", color="red"))).add_to(m)
    if not alarm_list:
        m = folium.Map(location=[37.3823, 127.1196],zoom_start=14, height=400)
        folium.TileLayer('cartodbpositron').add_to(m)

    maps = m._repr_html_()
    
    datas['map'] = maps
    datas['alarm_list'] = alarm_list
    
    # ====================== 사고 가져오기 ======================
    # 일시 기준 최신 순으로 모든 사고 정렬 
    # to-do : 일정 기간만 넣기 (현 시점으로는 데이터가 몇 개 없어서 전부로 진행함) [추후 수정]
    acc_list = Accident.objects.filter(locate__exact=dist_id).order_by('-date')
    
    datas['acc_list'] = acc_list
    
    # =====================최근 댓글 목록(3개) ====================
    notice_list = Notice.objects.filter(user_id__exact=request.user)
    notice_list = notice_list.filter(locate__exact=dist_id)
    reply_list = Reply.objects.filter(notice_id__in=notice_list).order_by('-create_time')
    
    if len(reply_list) > 3:
        reply_list = reply_list[:3]
    elif len(reply_list) == 0:
        reply_list = None
    
    datas['reply_list'] = reply_list
    
    # ==============  시간 별 알람 현황 (12시간) - 라인 차트   =============
    now = datetime.datetime.now()
    h_labels = []
    chart_alarm = []
    for i in range(12):
        h = now - datetime.timedelta(hours=i)
        h_labels.append(str(h.hour)+"시")
        
        hour_start = h.strftime("%Y-%m-%d %H:00:00")
        hour_end = h.strftime("%Y-%m-%d %H:59:59")
        
        hour_alarm = alarm_list.filter(date__range=[hour_start, hour_end]).count()
        chart_alarm.append(hour_alarm)
    h_labels.reverse()
    chart_alarm.reverse()
    
    datas['h_labels'] = h_labels
    datas['chart_alarm'] = chart_alarm
    
    # ==============  일 별 알람 현황 (30일) - 라인 차트   =============
    d_labels = []
    day_chart = []
    for i in range(15):
        d = now - datetime.timedelta(days=i)
        d_labels.append(d.strftime("%m월 %d일"))
        
        day_start = d.strftime("%Y-%m-%d 00:00:00")
        day_end = d.strftime("%Y-%m-%d 23:59:59")
        
        day_alarm = alarm_list.filter(date__range=[day_start, day_end]).count()
        day_chart.append(day_alarm)
    d_labels.reverse()
    day_chart.reverse()
    
    datas['d_labels'] = d_labels
    datas['day_chart'] = day_chart
    
    return render(request, 'dash/district.html',datas)

def company_table(request,dist_id):
    company_list = Company.objects.filter(locate__exact=dist_id)
    data = {'dist_id':dist_id, 'company_list':company_list}
    return render(request, 'dash/company_table.html', data)

def alarm_table(request,dist_id):
    company_list = Company.objects.filter(locate__exact=dist_id)
    group_list = Group.objects.filter(company_id__in=company_list)
    alarm_list = Alarm.objects.filter(group_id__in=group_list).order_by('-date')
    data = {'dist_id':dist_id, 'alarm_list':alarm_list}
    return render(request, 'dash/alarm_table.html', data)

def accident_table(request,dist_id):
    acc_list = Accident.objects.filter(locate__exact=dist_id).order_by('-date')
    data = {'dist_id':dist_id, 'acc_list':acc_list}
    return render(request, 'dash/accident_table.html', data)

def status_table(request,dist_id):
    company_list = Company.objects.filter(locate__exact=dist_id)
    emo_list  = Emotion.objects.filter(company_id__in=company_list)
    data = {'dist_id':dist_id, 'emo_list':emo_list}
    return render(request, 'dash/status_table.html', data)

"""
def acc_create(request):
    if request.method == 'POST':
        form = AccidentForm(request.POST)
        if form.is_valid():
            notice = form.save(commit=False)
            notice.create_time = timezone.now()
            notice.author = request.user  # 로그인 계정 저장
            notice.save()
            return redirect('board:index')
    else:
        form = NoticeForm()
    context = {'form': form}
    return render(request, 'dash/accident_table.html')
"""

webpage/bigproject/templates/dash/acc_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">사고 등록</h5>
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %} 

        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>

        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

webpage/bigproject/templates/dash/accident_table.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-success">{{dist_id}} 사고 현황</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive" style="overflow-x:hidden">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0" >
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>날짜</th>
                            <th>부상 정도</th>
                            <th>원인</th>
                            <th>그룹</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for acc in acc_list %}
                        <tr>
                            <td>{{acc.accident_id}}</td>
                            <td>{{acc.date}}</td>
                            <td>{{acc.injury}}</td>
                            <td>{{acc.cause}}</td>
                            <td>{{acc.group_id}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
<script src="{% static 'dash/vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'dash/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<script src="{% static 'dash/js/datatables.js' %}"></script>
{% endblock %}

webpage/bigproject/templates/dash/alarm_table.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-success">{{dist_id}} 알람 현황</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive" style="overflow-x:hidden">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0" >
                    <thead>
                        <tr>
                            <th>발생일</th>
                            <th>그룹</th>
                            <th>위도</th>
                            <th>경도</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for alarm in alarm_list %}
                        <tr>
                            <td>{{alarm.date}}</td>
                            <td>{{alarm.group_id}}</td>
                            <td>{{alarm.latitude}}</td>
                            <td>{{alarm.longitude}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
<script src="{% static 'dash/vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'dash/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<script src="{% static 'dash/js/datatables.js' %}"></script>
{% endblock %}

webpage/bigproject/templates/dash/district.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Begin Page Content -->
{% if 'g' in user.company_id.company_id %}
{% if user.address == '성남시' or user.address == dist_id %}
<div class="container-fluid">
    
    <!-- Page Heading -->
    <div class="card bg-success text-white shadow h-200 py-2 align-items-center">
        <h1 class="h4 mb-0 text-white ">  {{ dist_id }} - Dashboard</h1>
    </div>
    <br>

    <!-- alarms Row -->
    <div class="row">
        <div class='col-md-9' id='map' style="height:400px">
            <!-- map -->
            {{map|safe}}
        </div>

        <div class='col-md-3'>
            <!-- Alarms (Daily) Card  -->
            <div class="col-xl">
                <div class="card bg-warning text-white shadow h-200">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div>  알람 </div>
                                <div>  {{alarm_list|length}}</div>
                            </div>
                            <div class="col-auto">
                                <a href="{% url 'dash:alarm_table' dist_id %}" class="btn btn-danger btn-circle">
                                    <i class="fas fa-exclamation-triangle"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Accidents (Weekly) Card -->
            <div class="col-xl">
                <div class="card bg-danger text-white shadow h-200">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div>  사고 </div>
                                <div>  {{ acc_list|length }} </div>
                            </div>
                            <div class="col-auto">
                                <a href="{% url 'dash:accident_table' dist_id %}" class="btn btn-warning btn-circle">
                                    <i class="fas fa-exclamation-triangle"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Notice Card -->
            <div class='col-xl'>
                <div class="card shadow mb-4">
                    <div
                        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-success">공지-최근 댓글</h6>
                        <a href="{% url 'board:index' %}" class="btn btn-success btn-circle">
                            <i class="fas fa-info-circle"></i>
                        </a>
                    </div>
                    <div class="card-body">
                        {% for reply in reply_list %}
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <span class="text-xs font-weight-bold text-success mb-1"> {{ reply.notice_id }}</span><br>
                                <span class="mb-0 mr-3 text-gray-700">{{ reply.content }}</span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <br>

    <!-- line Chart -->
    <div class='row'>
        <div class="card shadow col-xl">
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-success" id = 'overview-title'> 지난 12시간 overview </h6>
                
                <div>
                    <a class="btn btn-success" id='overview-month'>
                        <span class="text">지난 15일 </span>
                    </a>
                    <span></span>
                    <a class="btn btn-success " id='overview-time'>
                        <span class="text">지난 12시간 </span>
                    </a>
                </div>

            </div>
            <div class="card-body" id = "one-month" style="display:none">
                <script>
                    var d_labels = {{d_labels|safe}};
                    var day_chart = {{day_chart}};
                </script>

                <div class="chart-area">
                    <canvas id="myAreaChart" ></canvas>
                </div>
            </div>

            <div class="card-body" id = "twelve">
                <script>
                    var h_labels = {{h_labels|safe}};
                    var chart_alarm = {{chart_alarm}};
                </script>

                <div class="chart-area">
                    <canvas id="myBarChart" ></canvas>
                </div>
            </div>
        </div>
    </div>

    <br>

    <!-- Pie Chart -->
    <div class="row">
        <div class='col-md-3'>
            <div class="card shadow mb-4">
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-success">위탁업체 현황</h6>
                    <a href="{% url 'dash:company_table' dist_id %}" class="btn btn-success btn-circle">
                        <i class="fas fa-info-circle"></i>
                    </a>
                </div>
                <script>
                    var chart_company = {{chart_company}};
                    var co_labels = {{co_labels|safe}};
                </script>
                <div class="card-body">
                    <div class="chart-pie pt-4 pb-2">
                        <canvas id="myPieChart"></canvas>
                    </div>
                </div>
            </div>
        </div>

        <div class='col-md-4'>
            <!-- 근로자 상태 모니터링-->
            <div class="card shadow mb-4">
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-success">근로자 근무일지 현황</h6>
                    <a href="{% url 'dash:status_table' dist_id %}" class="btn btn-success btn-circle">
                        <i class="fas fa-info-circle"></i>
                    </a>
                </div>
                <div class="card-body">
                    {% for emo in emo_list %}
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1"> {{ emo.name }}
                            {% if emo.done < emo.workers %}
                                ( {{emo.done}}명 완료 / 총 {{emo.workers}}명)
                            {% else %}
                                (전체 완료.)
                            {% endif %}
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ emo.percent }}%</div>
                                </div>
                                <div class="col">
                                    <div class="progress progress-sm mr-2">
                                        <div class="progress-bar bg-success" role="progressbar"
                                            style="width: {{ emo.percent }}%" aria-valuenow="{{ emo.percent }}" aria-valuemin="0"
                                            aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class='col-md-5'>
            <div class='col-xl'>
                <div class="card shadow mb-4">
                    <div
                        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-success"> 단어 빈출</h6>
                    </div>
                    <div class="card-body">
                        <div class="row no-gutters" >
                            <div class="col-md-6" >
                                <div class="border-bottom-success text-success"> 긍정</div>
                                {% for g,s in good_li %}
                                <div class="col mr-2">
                                    <span class="text-xs font-weight-bold text-success mb-1"> {{s}}</span>
                                    <span class="mb-0 mr-3 text-gray-800">{{g}}</span>
                                </div>
                                {% endfor %}
                            </div>

                            <div class="col-md-6" >
                                <div class="border-bottom-warning text-warning"> 부정</div>
                                {% for b,s in bad_li %}
                                <div class="col mr-2">
                                    <span class="text-xs font-weight-bold text-warning mb-1"> {{s}}</span>
                                    <span class="mb-0 mr-3 text-gray-800">{{b}}</span>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- 실시간 알림 -->
<div id="toast" class="alertalarm"></div>
{% else %}
<h2> {{dist_id}} 관리 권한이 없습니다. </h2>
{% endif %}

{% else %}
<h2> 접근 권한이 없습니다. </h2>
{% endif %}

{% endblock %}


{% block script %}

<!-- Page level plugins -->
<script src="{% static 'dash/vendor/chart.js/Chart.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'dash/js/chart-area.js' %}"></script>
<script src="{% static 'dash/js/chart-bar-day.js' %}"></script>
<script src="{% static 'dash/js/chart-pie.js' %}"></script>

<!-- ajax -->
<script type="text/javascript">
$(".alertalarm").ready(function(){
    timer = setInterval(
        function(){
            $.ajax({
                type: "POST", 
                url: "{% url 'dash:alertalarm' %}", 
                data: {'csrfmiddlewaretoken': '{{ csrf_token }}',
                        'dist_id': '{{dist_id}}'}, 
                dataType: "json", 
                success: function(response){
                    if(response.message){
                        toast(response.message);
                    }
                },
                error: function(request, status, error){ 
                    alert("error.")
                },
        });
},30000);})

let removeToast;

function toast(string) {
    const toast = document.getElementById("toast");

    toast.classList.contains("reveal") ?
        (clearTimeout(removeToast), removeToast = setTimeout(function () {
            document.getElementById("toast").classList.remove("reveal")
        }, 1000)) :
        removeToast = setTimeout(function () {
            document.getElementById("toast").classList.remove("reveal")
        }, 5000)
    toast.classList.add("reveal"),
        toast.innerHTML = string
}

let title = document.querySelector("#overview-title");

document.querySelector("#overview-month").addEventListener('click', function() {
    $("#twelve").hide();
    $("#one-month").show();
    title.innerHTML = "지난 15일 overview";
});
document.querySelector("#overview-time").addEventListener('click', function() {
    $("#twelve").show();
    $("#one-month").hide();
    title.innerHTML = "지난 12시간 overview";
});


</script>

{% endblock %}