webpage/bigproject/bigproject/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views, notice_views
import common.views as common_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('safe.urls')),
    path('board/',include('board.urls')), # 이거랑
    path('board/', base_views.index, name='index'), # 해결 필요 : 어째서 둘 다 해야 작동하지?
    path('common/',include('common.urls')),
    path('common/profile',common_views.profile_view, name='profile'),
    path('dash/',include('dash.urls')),
    path('emotion/', include(('emotion.urls', 'emotion'), namespace='emotion')),
    path('board/<int:notice_id>/download', notice_views.FileDownloadView.as_view(), name="download"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webpage/bigproject/board/urls.py
from django.urls import path
from .views import base_views, notice_views, reply_views

app_name = 'board'
urlpatterns=[
    #base_views
    path('', base_views.index, name='index'),
    path('<int:notice_id>/', base_views.detail, name='detail'),
    
    #notice_views
    path('notice/create/', notice_views.notice_create, name='notice_create'),
    #NoticeCreateView
    path('notice/modify/<int:notice_id>/', notice_views.notice_modify, name='notice_modify'),
    path('notice/delete/<int:notice_id>/', notice_views.notice_delete, name='notice_delete'),
    
    #reply_views
    path('notice/create/<int:notice_id>', reply_views.reply_create, name='reply_create'),
    path('reply/modify/<int:reply_id>/', reply_views.reply_modify, name='reply_modify'),
    path('reply/delete/<int:reply_id>/', reply_views.reply_delete, name='reply_delete'),
]

webpage/bigproject/common/urls.py
from django.urls import path
from . import views

app_name = 'common'
urlpatterns = [
    path('main/', views.main_view, name='main'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('recovery/id/', views.RecoveryIdView.as_view(), name='recovery_id'),
    path('recovery/pw/', views.RecoveryPwView.as_view(), name='recovery_pw'),
    path('recovery/id/find/', views.ajax_find_id_view, name='ajax_id'),
    path('recovery/pw/find/', views.ajax_find_pw_view, name='ajax_pw'),
    path('recovery/pw/auth/', views.auth_confirm_view, name='recovery_auth'),
    path('recovery/pw/reset/', views.auth_pw_reset_view, name='recovery_pw_reset'),
    # path('recovery/reset/', views.AuthPwResetView.as_view(), name='recovery_pw_reset'),

    path('agreement/', views.AgreementView.as_view(), name='agreement'),
    # path('register/', views.register_view, name='register'),
    # path('register/', views.RegisterView.as_view(), name='register'),
    # path('csregister/', views.cs_register_view, name='csregister'),
    path('csregister/', views.CsRegisterView.as_view(), name='csregister'),
    path('registerauth/', views.register_success, name='register_success'),
    path('activate/<str:uid64>/<str:token>/', views.activate, name='activate'),
    
    path('profile/', views.profile_view, name='profile'),
    path('profile/update/', views.profile_update_view, name='profile_update'),
    path('profile/password/', views.password_edit_view, name='password_edit'),
    path('profile/delete/', views.profile_delete_view, name='profile_delete'),
    
    path('pipp/', views.pipp_view, name='pipp'),
    path('tac/', views.tac_view, name='tac'),

]

webpage/bigproject/dash/urls.py
from django.urls import path
from . import views

app_name = 'dash'
urlpatterns = [
    path('', views.mainboard, name='main'),
    path('<str:dist_id>', views.district, name='district'),
    path('alertalarm/',views.alertalarm, name='alertalarm'),
    path('company_table/<str:dist_id>', views.company_table, name='company_table'),
    path('alarm_table/<str:dist_id>', views.alarm_table, name='alarm_table'),
    path('accident_table/<str:dist_id>', views.accident_table, name='accident_table'),
    path('status_table/<str:dist_id>', views.status_table, name='status_table'),
    #path('acc_create/', views.acc_create, name='acc_create'),
]

webpage/bigproject/board/views/base_views.py
#기본관리
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from ..models import Notice
from django.db.models import Q

@login_required(login_url='common:login')
def index(request):
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')  # 검색어
    # 작성일시 기준 최신 순으로 정렬
    notice_list = Notice.objects.order_by('-create_time')
    if not request.user.company_id.locate == '성남시':
        notice_list = notice_list.filter(locate__exact=request.user.company_id.locate)
    if kw:
        notice_list = notice_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(reply__content__icontains=kw) |  # 댓글 내용 검색
            Q(reply__author__username__icontains=kw)  # 댓글 글쓴이 검색
        ).distinct()
    # 페이지당 10개씩 보여주는 기능
    paginator = Paginator(notice_list, 10)  
    page_obj = paginator.get_page(page)
    context = {'notice_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'board/notice_list.html', context)

@login_required(login_url='common:login')
def detail(request,notice_id):
    notice = get_object_or_404(Notice,pk=notice_id)
    context = {'notice': notice}
    return render(request, 'board/notice_detail.html', context)

webpage/bigproject/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    -->
    <link rel="stylesheet" type="text/css" href="{% static 'emotion/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'dash/css/sb-admin-2.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'dash/css/custom.css' %}">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Custom fonts-->
    <link rel="stylesheet" type="text/css" href="{% static 'dash/vendor/fontawesome-free/css/all.min.css' %}" >
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    {% block header %}
    {% endblock %}

    <title> Safe Guard </title>
</head>
<body id="page-top">
    <div id="wrapper">  
        <!-- 네비게이션 사이드바 -->
        {% include "nav_sidebar.html" %}

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                <!-- 네비게이션 탑바 -->
                {% include "nav_topbar.html" %}
                {% block content %}
                {% endblock %}
            </div>

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>&copy; Safe Guard 2022</span>
                        <a href="#" onclick="window.open('{% url 'common:pipp' %}','win2','scrollbars=yes width=650, height=700');return false">개인정보 처리방침</a>
                        <a href="#" onclick="window.open('{% url 'common:tac' %}','win2','scrollbars=yes width=650, height=700');return false">이용약관</a>
                        </div>
                    </div>
                </div>
                <div style="display:none">
                    <img src="{% url 'video_feed' %}">
                    <img src="{% url 'detect' %}">
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
    </div>


    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'dash/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'dash/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'dash/js/sb-admin-2.min.js' %}"></script>

    <!-- 자바스크립트 -->
    {% block script %}
    {% endblock %}

    </body>
</html>

webpage/bigproject/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

webpage/bigproject/templates/nav_sidebar.html
<!-- 네비게이션바 -->
{% load static %}

<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-success sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <li class="nav-item active">
        <a class="nav-link" href="/">
            <i class="fas fa-hand-holding-medical"></i>
            <span>Safe Guard</span></a>
    </li>

    {% if 'g' in user.company_id.company_id %}
    {% if user.company_id.address == '성남시' %}
    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Detect AI
    </div>

    <!-- Nav Item -->
    <li class="nav-item">
        <a class="nav-link collapsed" onClick="location.href='http://172.30.1.97:8000/car/'" data-toggle="collapse" data-target="#collapseTwo"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-truck-moving"></i>
            <span>car detect</span>
        </a>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-walking"></i>
            <span>human detect</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header"> human detect:</h6>
                <a class="collapse-item" onClick="location.href='http://172.30.1.97:8000/robo/'">roboflow-api</a>
                <a class="collapse-item" onClick="location.href='http://172.30.1.97:8000/sanitationWorker/'">환경미화원-detect</a>
            </div>
        </div>
        
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">
    {% endif %}
    {% endif %}

    <!-- Heading -->
    <div class="sidebar-heading">
        Board
    </div>

    <!-- Nav Item - notice -->
    <li class="nav-item">
        <a class="nav-link" href="{% url 'board:index' %}">
            <i class="fas fa-fw fa-sign"></i>
            <span>공지 게시판</span></a>
    </li>

    <!-- Nav Item - Dashboard -->
    {% if 'g' in user.company_id.company_id %}
    <li class="nav-item">
            {% if user.company_id.address == '성남시' %}
            <a class="nav-link" href="{% url 'dash:main' %}">
                <i class="fas fa-calendar-week"></i>
                <span>최고 관리자 대시보드</span>
            </a>
            {% else %}
            <a class="nav-link" href="{% url 'dash:district' user.address %}">
                <i class="fas fa-calendar-week"></i>
                <span>구 관리자 대시보드</span>
            </a>
            {% endif %}
    </li>
    {% endif %}

    <!-- Nav Item - Emotion -->
    <li class="nav-item">
        <a class="nav-link" href="{% url 'emotion:main' %}">
            <i class="fas fa-fw fa-microphone"></i>
            <span>근무 일지</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->

webpage/bigproject/templates/nav_topbar.html
<!-- 네비게이션바 -->
{% load static %}

<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">3+</span>
            </a>
            <!-- Dropdown - Alerts -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                    Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-success">
                            <i class="fas fa-file-alt text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 12, 2019</div>
                        <span class="font-weight-bold">A new monthly report is ready to download!</span>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-success">
                            <i class="fas fa-donate text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 7, 2019</div>
                        $290.29 has been deposited into your account!
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
            </div>
        </li>

        <li class="nav-item  no-arrow">
            <a class="nav-link" href="#" data-toggle="modal" data-target="#logoutModal">
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-600 small"></i>
                Logout
            </a>
        </li>


        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small"> {{ user.name }}님, 환영합니다.</span>
            </a>
            
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'common:profile' %}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    My page
                </a>
        </li>

    </ul>

</nav>
<!-- End of Topbar -->

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">로그아웃 하시겠습니까?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">취소</button>
                <a class="btn btn-success" href="{% url 'common:logout' %}">로그아웃</a>
            </div>
        </div>
    </div>
</div>

webpage/bigproject/templates/user_base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <title>3조 빅프</title>
    <meta charset='utf-8'>
 
    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" />
    <!-- CheckBoxCSS -->
    <link rel="stylesheet" href="{% static 'common/css/checkbox.css' %}" type="text/css">
    <!-- StyleCSS -->
    <link rel="stylesheet" href="{% static 'common/css/style.css' %}" type="text/css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.11.0/css/mdb.min.css" rel="stylesheet">

    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js">
    </script>
    <!-- Bootstrap core JavaScript 
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script> -->
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.11.0/js/mdb.min.js">
    </script>

    {% block header %}
    {% endblock %}
</head>

<body style="background-color: #d6d6d6;"> 
    {% block contents %}
    {% endblock %}
    
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>

    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->

    {% if messages %}
    {% for message in messages %}
    {% if message.tags %}
    <script>
        alert("{{ message.message }}")
    </script>
    {% endif %}
    {% endfor %}
    {% endif %}
</body>

</html>