webpage/bigproject/bigproject/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views, notice_views
import common.views as common_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('safe.urls')),
    path('board/',include('board.urls')), # 이거랑
    path('board/', base_views.index, name='index'), # 해결 필요 : 어째서 둘 다 해야 작동하지?
    path('common/',include('common.urls')),
    path('common/profile',common_views.profile_view, name='profile'),
    path('dash/',include('dash.urls')),
    path('emotion/', include(('emotion.urls', 'emotion'), namespace='emotion')),
    path('board/<int:notice_id>/download', notice_views.FileDownloadView.as_view(), name="download"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webpage/bigproject/board/urls.py
from django.urls import path
from .views import base_views, notice_views, reply_views

app_name = 'board'
urlpatterns=[
    #base_views
    path('', base_views.index, name='index'),
    path('<int:notice_id>/', base_views.detail, name='detail'),
    
    #notice_views
    path('notice/create/', notice_views.notice_create, name='notice_create'),
    #NoticeCreateView
    path('notice/modify/<int:notice_id>/', notice_views.notice_modify, name='notice_modify'),
    path('notice/delete/<int:notice_id>/', notice_views.notice_delete, name='notice_delete'),
    
    #reply_views
    path('notice/create/<int:notice_id>', reply_views.reply_create, name='reply_create'),
    path('reply/modify/<int:reply_id>/', reply_views.reply_modify, name='reply_modify'),
    path('reply/delete/<int:reply_id>/', reply_views.reply_delete, name='reply_delete'),
]

webpage/bigproject/dash/urls.py
from django.urls import path
from . import views

app_name = 'dash'
urlpatterns = [
    path('', views.mainboard, name='main'),
    path('<str:dist_id>', views.district, name='district'),
    path('alertalarm/',views.alertalarm, name='alertalarm'),
    path('company_table/<str:dist_id>', views.company_table, name='company_table'),
    path('alarm_table/<str:dist_id>', views.alarm_table, name='alarm_table'),
    path('accident_table/<str:dist_id>', views.accident_table, name='accident_table'),
    path('status_table/<str:dist_id>', views.status_table, name='status_table'),
    #path('acc_create/', views.acc_create, name='acc_create'),
]

webpage/bigproject/board/models.py
from django.db import models
from common.models import Company, User
import os


# 공지사항
class Notice(models.Model):
    #company_id=models.ForeignKey(Company,on_delete=models.CASCADE) #공지를 확인할 수 있는 하청
    locate = models.CharField(max_length=200) # 어느 구 공지인지?
    subject = models.CharField(max_length=200) #제목
    content = models.TextField() #내용
    create_time = models.DateTimeField()
    user_id = models.ForeignKey(User, on_delete=models.CASCADE) #작성자 id
    modify_date = models.DateTimeField(null=True, blank=True) #수정일
    file = models.FileField(upload_to="uploads/",null=True, blank=True) # 파일 업로드 (...)
    
    def __str__(self):
        return self.subject
    def get_filename(self):
        return os.path.basename(self.file.name)
    
#댓글
class Reply(models.Model):
    notice_id= models.ForeignKey(Notice,on_delete=models.CASCADE)
    content = models.TextField()
    create_time = models.DateTimeField()
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    modify_date = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        return self.content

webpage/bigproject/board/forms.py
from django import forms
from .models import Notice, Reply

class NoticeForm(forms.ModelForm):
    upload = forms.FileField(label='첨부 파일', required=False, widget=forms.FileInput(attrs={'class': 'form'}))
    class Meta:
        model = Notice
        fields = ['subject', 'content','file']

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['content']
        labels = {
            'content': '댓글 내용',
        }

webpage/bigproject/board/views/base_views.py
#기본관리
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from ..models import Notice
from django.db.models import Q

@login_required(login_url='common:login')
def index(request):
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')  # 검색어
    # 작성일시 기준 최신 순으로 정렬
    notice_list = Notice.objects.order_by('-create_time')
    if not request.user.company_id.locate == '성남시':
        notice_list = notice_list.filter(locate__exact=request.user.company_id.locate)
    if kw:
        notice_list = notice_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(reply__content__icontains=kw) |  # 댓글 내용 검색
            Q(reply__author__username__icontains=kw)  # 댓글 글쓴이 검색
        ).distinct()
    # 페이지당 10개씩 보여주는 기능
    paginator = Paginator(notice_list, 10)  
    page_obj = paginator.get_page(page)
    context = {'notice_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'board/notice_list.html', context)

@login_required(login_url='common:login')
def detail(request,notice_id):
    notice = get_object_or_404(Notice,pk=notice_id)
    context = {'notice': notice}
    return render(request, 'board/notice_detail.html', context)

webpage/bigproject/board/views/notice_views.py
# 공지관리
from django.shortcuts import render, get_object_or_404,redirect
from django.utils import timezone
from django.contrib import messages

from django.views.generic.edit import FormView
from django.urls import reverse_lazy

from django.views.generic.detail import SingleObjectMixin
from django.http import FileResponse
from django.core.files.storage import FileSystemStorage
from board.models import Notice
from django.views.generic import View
# Create your views here.

from ..models import Notice
from ..forms import NoticeForm
from django.contrib.auth.decorators import login_required

@login_required(login_url='common:login')
def notice_create(request):
    if request.method == 'POST':
        form = NoticeForm(request.POST)
        if form.is_valid():
            notice = form.save(commit=False)
            notice.create_time = timezone.now()
            notice.locate = request.user.address
            notice.user_id = request.user  # 로그인 계정 저장
            if request.FILES:
                notice.file = request.FILES['file']
            
            notice.save()
            return redirect('board:index')
    else:
        form = NoticeForm()
    context = {'form': form}
    return render(request, 'board/notice_form.html', context)

@login_required(login_url='common:login')
def notice_modify(request, notice_id):
    notice = get_object_or_404(Notice, pk=notice_id)
    if request.user != notice.user_id:
        messages.error(request, '수정 권한이 없습니다')
        return redirect('board:detail', notice_id=notice.id)
    if request.method == "POST":
        form = NoticeForm(request.POST, instance=notice)
        if form.is_valid():
            notice = form.save(commit=False)
            notice.modify_date = timezone.now()  # 수정일시 저장
            notice.save()
            return redirect('board:detail', notice_id=notice.id)
    else:
        form = NoticeForm(instance=notice)
    context = {'form': form}
    return render(request, 'board/notice_form.html', context)

@login_required(login_url='common:login')
def notice_delete(request, notice_id):
    notice = get_object_or_404(Notice, pk=notice_id)
    if request.user != notice.user_id:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('board:detail', notice_id=notice.id)
    notice.delete()
    return redirect('board:index')


class FileDownloadView(SingleObjectMixin, View):
    def get(self, request, notice_id):
        object = get_object_or_404(Notice, pk=notice_id)
        file_path = object.file.path
        #file_type = object.content_type  # django file object에 content type 속성이 없어서 따로 저장한 필드
        fs = FileSystemStorage(file_path)
        response = FileResponse(fs.open(file_path, 'rb')) #, content_type=file_type)
        response['Content-Disposition'] = f'file; filename={object.get_filename()}'
        return response

webpage/bigproject/board/views/reply_views.py
#댓글관리

from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from django.contrib import messages

# Create your views here.

from ..models import Notice, Reply
from ..forms import  ReplyForm
from django.contrib.auth.decorators import login_required

@login_required(login_url='common:login')
def reply_create(request, notice_id):
    notice = get_object_or_404(Notice,pk=notice_id)
    if request.method == "POST":
        form = ReplyForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.create_time = timezone.now()
            reply.notice_id = notice
            reply.user_id = request.user  # 로그인 계정 저장
            reply.save()
            return redirect('{}#reply_{}'.format(
                resolve_url('board:detail', notice_id=notice.id), reply.id))
    else:
        form = ReplyForm()
    context = {'notice': notice, 'form': form}
    return render(request, 'board/notice_detail.html', context)

@login_required(login_url='common:login')
def reply_modify(request, reply_id):
    reply = get_object_or_404(Reply, pk=reply_id)
    if request.user != reply.user_id:
        messages.error(request, '수정권한이 없습니다')
        return redirect('board:detail', reply_id=reply.notice_id.id)
    if request.method == "POST":
        form = ReplyForm(request.POST, instance=reply)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.modify_date = timezone.now()
            reply.save()
            return redirect('{}#reply_{}'.format(
                resolve_url('board:detail', notice_id=reply.notice_id.id), reply.id))
    else:
        form = ReplyForm(instance=reply)
    context = {'reply': reply, 'form': form}
    return render(request, 'board/reply_form.html', context)

@login_required(login_url='common:login')
def reply_delete(request, reply_id):
    reply = get_object_or_404(Reply, pk=reply_id)
    if request.user != reply.user_id:
        messages.error(request, '삭제권한이 없습니다')
    else:
        reply.delete()
    return redirect('board:detail', notice_id=reply.notice_id.id)

webpage/bigproject/templates/board/notice_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container justify-content-center">
    <!-- message 표시 -->
    {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}

    <div class="col-lg-12">
        <article>
            <header class="mb-4 border-bottom-success">
                <h1 class="mb-1 text-gray-900"> {{ notice.subject }} 
                    <!-- 로그인 된 계정이 작성자와 일치 시 표시되는 버튼 시작-->
                    <div class="my-3 float-right">
                        {% if request.user == notice.user_id %}
                        <a href="{% url 'board:notice_modify' notice.id  %}" 
                        class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                        data-uri="{% url 'board:notice_delete' notice.id  %}">삭제</a>
                        {% endif %}
                    </div>
                    <!-- 로그인 된 계정이 작성자와 일치 시 표시되는 버튼 끝-->
                </h1>
                <cite> {{ notice.create_time }} </cite>
                <cite> | 작성자 : {{ notice.user_id.name }} </cite>
            </header>
            <section class="mb-5">
                <div class="fs-5 mb-4" style="white-space:break-spaces;">{{ notice.content }} </div>

                <!-- 파일 다운로드 -->
                {% if notice.get_filename %}
                <div>
                    <span class="text-success">별첨 | {{ notice.get_filename }}</span>
                    <form action='{% url "download" notice.id %}'>
                        <button class="btn btn-sm btn-outline-secondary" type="submit">
                            <span class="text">다운로드</span>
                        </button>
                    </form>
                </div>
                {% endif %}
            </section>
        </article>

        <!-- Comments section-->
        <section class="mb-5">
            <div class="card bg-light">
                <div class="card-body">
                    <!-- Comment form-->
                    {{notice.reply_set.count}}개의 댓글이 있습니다.
                    <form action="{% url 'board:reply_create' notice.id %}" method="post" class="mb-4">
                        {% csrf_token %}
                        {% include "form_errors.html" %} 
                        <div class="row">
                            <div class="form-group col-10">
                                <textarea {% if not user.is_authenticated %}disabled{% endif %} 
                                    name="content" id="content" class="form-control" rows="3" placeholder="답글 달기"></textarea>
                            </div>
                            <input type="submit" value="댓글 등록" class="btn btn-success col-2" style="height:86px">
                        </div>
                    </form>

                    <!-- Comment list-->
                    {% for reply in notice.reply_set.all %}
                    <a id="reply_{{ reply.id }}"></a>
                    <div class="d-flex mb-4">
                        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..."></div>
                        <div class="ms-3">
                            <div class="fw-bold text-success">{{ reply.user_id.name }}</div>
                            {{ reply.content }}
                        </div>
                        <div class="my-3t">
                            {% if request.user == reply.user_id %}
                            <a href="{% url 'board:reply_modify' reply.id  %}" 
                            class="btn btn-sm btn-outline-secondary">수정</a>
                            <a href="#" class="delete btn btn-sm btn-outline-success "
                            data-uri="{% url 'board:reply_delete' reply.id  %}">삭제</a>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </section>
    </div>
</div>

{% endblock %}

{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

webpage/bigproject/templates/board/notice_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">공지 등록</h5>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">파일</label>
            {{ form.file|default_if_none:'' }}
        </div>

        <button type="submit" class="btn btn-success">저장하기</button>
    </form>
</div>
{% endblock %}

webpage/bigproject/templates/board/notice_list.html
{% extends 'base.html' %}
{% load board_filter %}
{% block content %}
<div class="container-fluid">
<div class="container my-3">
    <div class="row my-3">
        {% if 'g' in user.company_id.company_id %}
        <div class="col-6">
            <a href="{% url 'board:notice_create' %}" class="btn btn-success">공지 등록</a>
        </div>
        {% endif %}
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
            {% if notice_list %}
            {% for notice in notice_list %}
            <tr class="text-center">
                <td>
                    <!-- 페이지 번호 순차적으로 정규화 시작 -->
                    {{ notice_list.paginator.count|sub:notice_list.start_index|sub:forloop.counter0|add:1 }}
                    <!-- 페이지 번호 순차적으로 정규화 끝 -->
                </td>
                <td class="text-start">
                    <a href="{% url 'board:detail' notice.id %}">{{ notice.subject }}</a>
                    <!-- 제목 옆에 댓글 수 출력 시작 -->
                    {% if notice.reply_set.count > 0 %}
                        <span class="text-danger small mx-2">{{ notice.reply_set.count }}</span>
                    {% endif %}
                    <!-- 제목 옆에 댓글 수 출력 끝 -->
                </td>
                <td>{{ notice.user_id.name }}</td>  <!-- 글쓴이 추가 -->
                <td>{{ notice.create_time}}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="4">공지가 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
    </table>

    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">

        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ notice_list.previous_page_number }}"
           href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}

        <!-- 페이지리스트 -->
        {% for page_number in notice_list.paginator.page_range %}
        <!-- 페이지 표시 제한 (전후 5페이지 까지) -->
        {% if page_number >= notice_list.number|add:-5 and page_number <= notice_list.number|add:5 %}
        {% if page_number == notice_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}

        <!-- 다음페이지 -->
        {% if notice_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ notice_list.next_page_number }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
</div>

<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>

{% endblock %}

<!-- page, kw 파라미터를 동시에 요청할 수 있는 자바스크립트 -->
{% block script %}
<script type='text/javascript'>
    const page_elements = document.getElementsByClassName("page-link");
    Array.from(page_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });
    const btn_search = document.getElementById("btn_search");
    btn_search.addEventListener('click', function() {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        document.getElementById('searchForm').submit();
    });
</script>
{% endblock %}

webpage/bigproject/templates/board/reply_form.html
{% extends 'base.html' %}
{% block content %}

<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}