webpage/bigproject/bigproject/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views, notice_views
import common.views as common_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('safe.urls')),
    path('board/',include('board.urls')), # 이거랑
    path('board/', base_views.index, name='index'), # 해결 필요 : 어째서 둘 다 해야 작동하지?
    path('common/',include('common.urls')),
    path('common/profile',common_views.profile_view, name='profile'),
    path('dash/',include('dash.urls')),
    path('emotion/', include(('emotion.urls', 'emotion'), namespace='emotion')),
    path('board/<int:notice_id>/download', notice_views.FileDownloadView.as_view(), name="download"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webpage/bigproject/common/urls.py
from django.urls import path
from . import views

app_name = 'common'
urlpatterns = [
    path('main/', views.main_view, name='main'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('recovery/id/', views.RecoveryIdView.as_view(), name='recovery_id'),
    path('recovery/pw/', views.RecoveryPwView.as_view(), name='recovery_pw'),
    path('recovery/id/find/', views.ajax_find_id_view, name='ajax_id'),
    path('recovery/pw/find/', views.ajax_find_pw_view, name='ajax_pw'),
    path('recovery/pw/auth/', views.auth_confirm_view, name='recovery_auth'),
    path('recovery/pw/reset/', views.auth_pw_reset_view, name='recovery_pw_reset'),
    # path('recovery/reset/', views.AuthPwResetView.as_view(), name='recovery_pw_reset'),

    path('agreement/', views.AgreementView.as_view(), name='agreement'),
    # path('register/', views.register_view, name='register'),
    # path('register/', views.RegisterView.as_view(), name='register'),
    # path('csregister/', views.cs_register_view, name='csregister'),
    path('csregister/', views.CsRegisterView.as_view(), name='csregister'),
    path('registerauth/', views.register_success, name='register_success'),
    path('activate/<str:uid64>/<str:token>/', views.activate, name='activate'),
    
    path('profile/', views.profile_view, name='profile'),
    path('profile/update/', views.profile_update_view, name='profile_update'),
    path('profile/password/', views.password_edit_view, name='password_edit'),
    path('profile/delete/', views.profile_delete_view, name='profile_delete'),
    
    path('pipp/', views.pipp_view, name='pipp'),
    path('tac/', views.tac_view, name='tac'),

]

webpage/bigproject/dash/urls.py
from django.urls import path
from . import views

app_name = 'dash'
urlpatterns = [
    path('', views.mainboard, name='main'),
    path('<str:dist_id>', views.district, name='district'),
    path('alertalarm/',views.alertalarm, name='alertalarm'),
    path('company_table/<str:dist_id>', views.company_table, name='company_table'),
    path('alarm_table/<str:dist_id>', views.alarm_table, name='alarm_table'),
    path('accident_table/<str:dist_id>', views.accident_table, name='accident_table'),
    path('status_table/<str:dist_id>', views.status_table, name='status_table'),
    #path('acc_create/', views.acc_create, name='acc_create'),
]

webpage/bigproject/common/models.py
from django.db import models
# Create your models here.
from django.contrib.auth.models import AbstractUser

# 하청회사
class Company(models.Model):
    company_id = models.CharField(max_length=200,primary_key=True) #회사 아이디, # PK값
    name = models.CharField(max_length=200) #회사 이름
    address = models.CharField(max_length=200) #회사 주소
    phone = models.CharField(max_length=200,null=True,blank=True) #전화번호
    start_date = models.DateTimeField(null=True, blank=True) #계약시작일
    exp_date=models.DateTimeField(null=True,blank=True) #계약만료일
    locate=models.CharField(max_length=200) #구
    workers = models.IntegerField(null=True,blank=True) # 근로자 수
    
    def __str__(self):
        return self.name

# 사용자 table
class User(AbstractUser):
    #user_id=models.CharField(max_length=200,primary_key=True) # 기본 모델 상속받아서 int로 자동 생성됨 (추후 수정)
    name=models.CharField(max_length=200) 
    #id=models.CharField(max_length=200) #-> 기본 모듈에서 아이디는 username 변수로 기능함
    password=models.CharField(max_length=200)
    address=models.CharField(max_length=200) # 어느 구 소속인지?
    phone=models.CharField(max_length=200)
    company_id=models.ForeignKey(Company,on_delete=models.CASCADE) #하청회사 아이디 / 슈퍼 유저 생성시 오류
    #group_id =models.ForeignKey(Group,on_delete=models.CASCADE) -> 상호 참조 오류
    auth = models.CharField(max_length=10, null=True)
    
    def __str__(self):
        return self.username
    
#근로그룹
class Group(models.Model):
    group_id=models.CharField(max_length=200,primary_key=True)
    job=models.CharField(max_length=200) #직무
    detail_locate=models.TextField(blank=True,null=True) #상세경로
    user_id=models.ForeignKey(User,on_delete=models.CASCADE) #근로자 아이디
    company_id=models.ForeignKey(Company,on_delete=models.CASCADE) #하청회사 아이디
    current=models.IntegerField() #현재인지 아닌지
    
    def __str__(self):
        return self.group_id

# 근로
class Working(models.Model):
    working_id=models.CharField(max_length=200,primary_key=True)
    group_id =models.ForeignKey(Group,on_delete=models.CASCADE)
    date=models.DateTimeField(null=True,blank=True)
    
    def __str__(self):
        return self.working_id

webpage/bigproject/common/views.py
from django.conf import settings
from django.utils.datastructures import MultiValueDictKeyError
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .decorators import login_message_required, admin_required, logout_message_required
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect, get_object_or_404
# from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, FormView, TemplateView
from django.views.generic import View
# from django.contrib.auth.views import PasswordResetConfirmView
from .models import User
from .forms import CsRegisterForm, LoginForm, CheckPasswordForm, RecoveryIdForm, RecoveryPwForm, CustomSetPasswordForm, CustomPasswordChangeForm, CustomUserChangeForm
from django.http import HttpResponse
import json
from django.core import serializers
from django.core.serializers.json import DjangoJSONEncoder
from .helper import send_mail, email_auth_num
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, Http404
from board.models import Notice
from django.forms.utils import ErrorList
from django.views.decorators.http import require_GET, require_POST
from django.core.exceptions import PermissionDenied


from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth.tokens import default_token_generator
from datetime import datetime
# from ipware.ip import get_ip


# 메인화면(로그인 후)
@login_message_required
def main_view(request):
    notice_list = Notice.objects.order_by('-user_id')[:5]

    context = {
        'notice_list' : notice_list,
    }
    return render(request, 'common/main.html', context)


# 로그인
@method_decorator(logout_message_required, name='dispatch')
class LoginView(FormView):
    template_name = 'common/login.html'
    form_class = LoginForm
    success_url = '/common/main/'

    def form_valid(self, form):
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            self.request.session['username'] = username
            login(self.request, user)

            # Session Maintain Test

            remember_session = self.request.POST.get('remember_session', False)
            if remember_session:
                settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = False

            # try:
            #     remember_session = self.request.POST['remember_session']
            #     if remember_session:
            #         settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = False
            # except MultiValueDictKeyError:
            #     settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = True
            
        return super().form_valid(form)


# 로그아웃
def logout_view(request):
    logout(request)
    return redirect('/')


# 회원가입 약관동의
@method_decorator(logout_message_required, name='dispatch')
class AgreementView(View):
    def get(self, request, *args, **kwargs):
        request.session['agreement'] = False
        return render(request, 'common/agreement.html')

    def post(self, request, *args, **kwarg):
        if request.POST.get('agreement1', False) and request.POST.get('agreement2', False):
            request.session['agreement'] = True
            if request.POST.get('csregister') == 'csregister':       
                return redirect('/common/csregister/')
            else:
                return redirect('/common/register/')
        else:
            messages.info(request, "약관에 모두 동의해주세요.")
            return render(request, 'common/agreement.html')   


# 회원가입 인증메일 발송 안내 창
def register_success(request):
    if not request.session.get('register_auth', False):
        raise PermissionDenied
    request.session['register_auth'] = False

    return render(request, 'common/register_success.html')


# 회원가입 
class CsRegisterView(CreateView):
    model = User
    template_name = 'common/register_cs.html'
    form_class = CsRegisterForm

    def get(self, request, *args, **kwargs):
        if not request.session.get('agreement', False):
            raise PermissionDenied
        request.session['agreement'] = False

        url = settings.LOGIN_REDIRECT_URL
        if request.user.is_authenticated:
            return HttpResponseRedirect(url)
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        # messages.success(self.request, "회원가입 성공.")
        self.request.session['register_auth'] = True
        messages.success(self.request, '회원님의 입력한 Email 주소로 인증 메일이 발송되었습니다. 인증 후 로그인이 가능합니다.')
        # return settings.LOGIN_URL
        return reverse('common:register_success')

    def form_valid(self, form):
        self.object = form.save()

        # 회원가입 인증 메일 발송
        # ISSUE - https 통신오류 -> http 프로토콜 수정
        send_mail(
            '[Safe Guard] {}님의 회원가입 인증메일 입니다.'.format(self.object.username),
            [self.object.email],
            html=render_to_string('common/register_email.html', {
                'user': self.object,
                'uid': urlsafe_base64_encode(force_bytes(self.object.pk)).encode().decode(),
                'domain': self.request.META['HTTP_HOST'],
                'token': default_token_generator.make_token(self.object),
            }),
        )
        return redirect(self.get_success_url())

"""
# 일반 회원가입
class RegisterView(CsRegisterView):
    template_name = 'common/register.html'
    form_class = RegisterForm
"""

# 이메일 인증 활성화
def activate(request, uid64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uid64))
        current_user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist, ValidationError):
        messages.error(request, '메일 인증에 실패했습니다.')
        return redirect('common:login')

    if default_token_generator.check_token(current_user, token):
        current_user.is_active = True
        current_user.save()

        messages.info(request, '메일 인증이 완료 되었습니다. 회원가입을 축하드립니다!')
        return redirect('common:login')

    messages.error(request, '메일 인증에 실패했습니다.')
    return redirect('common:login')


# 비밀번호 수정
@login_message_required
def password_edit_view(request):
    if request.method == 'POST':
        password_change_form = CustomPasswordChangeForm(request.user, request.POST)
        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)
            # logout(request)
            messages.success(request, "비밀번호를 성공적으로 변경하였습니다.")
            return redirect('common:profile')
    else:
        password_change_form = CustomPasswordChangeForm(request.user)

    return render(request, 'common/profile_password.html', {'password_change_form':password_change_form})


# 아이디찾기
@method_decorator(logout_message_required, name='dispatch')
class RecoveryIdView(View):
    template_name = 'common/recovery_id.html'
    recovery_id = RecoveryIdForm

    def get(self, request):
        if request.method=='GET':
            form_id = self.recovery_id(None)
        return render(request, self.template_name, { 'form_id':form_id, })


# 비밀번호찾기
@method_decorator(logout_message_required, name='dispatch')
class RecoveryPwView(View):
    template_name = 'common/recovery_pw.html'
    recovery_pw = RecoveryPwForm

    def get(self, request):
        if request.method=='GET':
            form_pw = self.recovery_pw(None)
            return render(request, self.template_name, { 'form_pw':form_pw, })


# 아이디찾기 AJAX 통신
def ajax_find_id_view(request):
    name = request.POST.get('name')
    email = request.POST.get('email')
    result_id = User.objects.get(name=name, email=email)
       
    return HttpResponse(json.dumps({"result_id": result_id.username}, cls=DjangoJSONEncoder), content_type = "application/json")    


# 비밀번호찾기 AJAX 통신
def ajax_find_pw_view(request):
    username = request.POST.get('username')
    name = request.POST.get('name')
    email = request.POST.get('email')
    result_pw = User.objects.get(username=username, name=name, email=email)

    if result_pw:
        auth_num = email_auth_num()
        result_pw.auth = auth_num 
        result_pw.save()

        send_mail(
            '[Safy Guard] 비밀번호 찾기 인증메일입니다.',
            [email],
            html=render_to_string('common/recovery_email.html', {
                'auth_num': auth_num,
            }),
        )
    # print(auth_num)
    return HttpResponse(json.dumps({"result": result_pw.username}, cls=DjangoJSONEncoder), content_type = "application/json")


# 비밀번호찾기 인증번호 확인
def auth_confirm_view(request):
    # if request.method=='POST' and 'auth_confirm' in request.POST:
    username = request.POST.get('username')
    input_auth_num = request.POST.get('input_auth_num')
    user = User.objects.get(username=username, auth=input_auth_num)
    # login(request, user)
    user.auth = ""
    user.save()
    request.session['auth'] = user.username  
    
    return HttpResponse(json.dumps({"result": user.username}, cls=DjangoJSONEncoder), content_type = "application/json")

        
# 비밀번호찾기 새비밀번호 등록
@logout_message_required
def auth_pw_reset_view(request):
    if request.method == 'GET':
        if not request.session.get('auth', False):
            raise PermissionDenied

    if request.method == 'POST':
        session_user = request.session['auth']
        current_user = User.objects.get(username=session_user)
        # del(request.session['auth'])
        login(request, current_user)

webpage/bigproject/templates/common/profile.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'common/css/profile.css' %}" type="text/css">
{% endblock %}

{% block content %}
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">Profile</h1>
    <div class="row">
        <div class="col-lg-6">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">내 정보</h6>
                </div>
                <div class="card-body">
                    <table style="color:black; margin-left:10px;">
                        <tr>
                            <td class="profile_title">아이디</td>
                            <td class="profile_content">{{ user.username }}</td>
                        </tr>
                        <tr>
                            <td class="profile_title">이메일</td>
                            <td class="profile_content">{{ user.email }}</td>
                        </tr>
                        <tr>
                            <td class="profile_title">이름 </td>
                            <td class="profile_content">{{ user.name }}</td>
                        </tr>
                        <tr>
                            <td class="profile_title">연락처</td>
                            <td class="profile_content">{{ user.phone }}</td>
                        </tr>
                        <tr>
                            <td class="profile_title">주소 
                            </td>
                            <td class="profile_content">{{ user.address }}</td>
                        </tr>
                        <tr>
                            <td class="profile_title">회사명</td>
                            <td class="profile_content">{{ user.company_id|default:'선택안함' }}</td>
                        </tr>
                    </table>
                    
                    <hr>
                    <div style="text-align: center;">
                    <!-- <div style="margin-left: 10px;"> -->
                        <a href="{% url 'common:profile_update' %}" style="color:#d14040f2; font-size:15px;"><i class="fas fa-user-edit"></i>&nbsp;내정보수정</a>&nbsp;&middot;&nbsp;
                        <a href="{% url 'common:password_edit' %}" style="color:#d14040f2; font-size:15px;"><i class="fas fa-user-lock"></i>&nbsp;비밀번호변경</a>&nbsp;&middot;&nbsp;
                        <a href="{% url 'common:profile_delete' %}" style="color:#d14040f2; font-size:15px;"><i class="fas fa-user-slash"></i>&nbsp;회원탈퇴</a> <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
{% endblock %}

webpage/bigproject/templates/common/recovery_pw.html
{% extends "user_base.html" %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'common/css/loading.css' %}" type="text/css">
{% endblock %}
{% block contents %}
    <div class="container">
        <div class="row justify-content-md-center">
            <div style="position: absolute; top: 45%; height: 504.18px; margin-top: -252.09px;">
                <div class="card" style="width: 32rem;">
                    <div class="card-body">
                        <div class="text-center">
                            <a href="/"><img src="{% static 'common/img/logo2.png' %}" style="width: 40%; margin-top:10px; margin-bottom: -30px;"></a>
                        </div>
                        <div class="row mt-5">
                            <div class="col-12">
                                {% csrf_token %}
                                <!--아이디-->
                                <div class="mb-4 md-form">
                                    <label name="label_username" for="{{ form_pw.username.id_for_label }}"><i
                                        class="fas fa-user"></i>&nbsp;&nbsp;{{ form_pw.username.label }}</label>
                                        {{ form_pw.username }}
                                </div>
                                <!--이름-->
                                <div class="mb-4 md-form">
                                    <label name="label_name" for="{{ form_pw.name.id_for_label }}"><i
                                        class="fas fa-user-edit"></i>&nbsp;&nbsp;{{ form_pw.name.label }}</label>
                                        {{ form_pw.name }}
                                </div>
                                <!--이메일-->
                                <div class="mb-4 md-form">
                                    <label name="label_email" for="{{ form_pw.email.id_for_label }}"><i
                                            class="fas fa-envelope"></i>&nbsp;&nbsp;{{ form_pw.email.label }}</label>
                                        {{ form_pw.email }}
                                    <small class="form-text text-muted">
                                        등록하신 메일로 인증번호가 발송됩니다.
                                    </small>
                                </div>
                                <!--비밀번호찾기 버튼-->
                                <div id="div_find_pw" style="padding-top:10px;" class="row justify-content-md-center">
                                    <button id="find_pw" class="btn btn-green" style="opacity: 90%; font-size: 16px;" name="recovery_pw"><i class="fas fa-search"></i>&nbsp;&nbsp;비밀번호찾기</button>
                                </div>
    
                                <div style="text-align: center; margin-top: 10px; margin-bottom: -10px;">
                                    <div id="loading"></div>
                                </div>
    
                                <div id="result_pw"></div>
    
                                <br>
                                <span style="color:gray; font-size: 14px;" >&middot;&nbsp;아이디를 잊으셨나요?</span>
                                <a style="text-decoration:underline; color:black; font-size: 14px;" href="{% url 'common:recovery_id' %}">아이디찾기</a>&nbsp;
                                <a style="text-decoration:underline; color:black; font-size: 14px;" href="{% url 'common:login' %}">로그인 페이지</a>
    
                                <script type="text/javascript">
                                    $(document).ready(function () {
                                        $('#find_pw').click(function () {
                                            $('#loading').replaceWith('<div id="loading_end" class="loading"></div>')
                                            var username = $("#pw_form_id").val();
                                            var name = $("#pw_form_name").val();
                                            var email = $("#pw_form_email").val();
    
                                            $.ajax({
                                                type: "POST",
                                                url: "/common/recovery/pw/find/",
                                                dataType: "json",
                                                data: {
                                                    'username': username,
                                                    'name': name,
                                                    'email': email,
                                                    'csrfmiddlewaretoken': '{{csrf_token}}',
                                                },
                                                success: function (response) {
                                                    $('#loading_end').remove()
                                                    alert('회원님의 이메일로 인증코드를 발송하였습니다.');
                                                    // $('#result_pw').replaceWith('<h5><p id="result_pw">회원님의 비밀번호는 <strong>'+response.result_pw+'</strong> 입니다.</p></h5>')
                                                    $('#div_find_pw').remove()
                                                    $('#result_pw').replaceWith(
                                                        '<hr><div class="row justify-content-md-center"><form class="form-inline" style="margin-bottom:-15px; margin-top:-10px;"><div class="md-form md-outline"><label for="input_auth_num">인증번호 입력 (<span id="timeset"></span>)</label><input type="text" id="input_auth_num" class="form-control mx-sm-2" autofocus/></div></form>'+
                                                        '<button type="submit" name="auth_confirm" id="id_auth_confirm" class="btn btn-green" style="opacity: 90%; height:30%; margin-top:10px; font-size: 12px;"><i class="fas fa-check"></i>&nbsp;&nbsp;인증확인</button></div><hr>'
                                                    )
                                                    function countdown( elementName, minutes, seconds ) {
                                                        var elementName, endTime, hours, mins, msLeft, time;
                                                        function twoDigits( n ) {
                                                            return (n <= 9 ? "0" + n : n);
                                                        }
                                                        function updateTimer() {
                                                            msLeft = endTime - (+new Date);
                                                            if ( msLeft < 1000 ) {
                                                                alert("인증시간이 초과되었습니다.");
                                                                $("" + elementName).remove();
                                                                cert_ok = false;
                                                                certificationNum = false;
                                                                location.href = "{% url 'common:recovery_pw' %}"
                                                            } else {
                                                                time = new Date( msLeft );
                                                                hours = time.getUTCHours();
                                                                mins = time.getUTCMinutes();
                                                                $("" + elementName).html((hours ? hours + ':' + twoDigits( mins ) : twoDigits(mins))
                                                                + ':' + twoDigits( time.getUTCSeconds()));
                                                                setTimeout( updateTimer, time.getUTCMilliseconds() + 500 );
                                                            }
                                                        }
                                                        endTime = (+new Date) + 1000 * (60*minutes + seconds) + 500;
                                                        updateTimer();
                                                    }
                                                    countdown("#timeset", 5, 0);
    
                                                    var user = response.result
    
                                                    $(document).ready(function () {
                                                        $('#id_auth_confirm').click(function () {
                                                            var input_auth_num = $("#input_auth_num").val();
    
                                                            $.ajax({
                                                                type: "POST",
                                                                url: "/common/recovery/pw/auth/",
                                                                dataType: "json",
                                                                data: {
                                                                    'username': user,
                                                                    'input_auth_num': input_auth_num,
                                                                    'csrfmiddlewaretoken': '{{csrf_token}}',
                                                                },
                                                                success: function (response) {
                                                                    // location.href = "/common/profile/password/";
                                                                    location.href = "{% url 'common:recovery_pw_reset' %}";
                                                                },
                                                                error: function () {
                                                                    if ($('#input_auth_num').val()=="") {
                                                                        alert('회원님의 이메일로 전송된 인증번호를 입력해주세요.');
                                                                    } else {
                                                                        alert('인증번호가 일치하지 않습니다.');
                                                                    }
                                                                },
                                                            });
                                                        })
                                                    })
                                                },
                                                error: function () {
                                                    $('#loading_end').remove()
                                                    if (username == "" || name == "" || email == "") {
                                                        alert('아이디, 이름, 이메일을 모두 입력해주세요.');
                                                    } else {
                                                        alert('입력하신 정보가 일치하지 않거나 존재하지 않습니다.');
                                                    }
                                                },
                                            });
                                        })
                                    });
                                </script>
                                <!-- {% if result_pw %}
                                <h5>회원님의 비밀번호는 <strong>{{ result_pw }}</strong>입니다.</h5>
                                {% endif %}
                                <br><br> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    {% endblock %}

webpage/bigproject/templates/common/register_email.html
{% autoescape off %}
<!DOCTYPE html>
<html>
<body>
    <div style="width:100%;min-width:100%;height:100%;">
        <div style="padding: 70px 0; background: #f7f8f9;">
            <div style="margin: 0 auto; width: 600px; color: #000;">
                <div style="padding: 30px 90px; text-align: center; border: 1px solid #dfdfdf; background: #fff;">
                    <h3 style="margin-bottom: 35px; font-size: 30px; font-weight: 600;">회원가입 이메일 인증 발송</h3>
                    <div style="padding: 10px 0 20px; border-top: 1px solid rgb(172, 172, 172);">
                        <p style="font-size: 14px; font-weight: 600; line-height: 20px;">Safe Guard 홈페이지 회원가입을 축하드립니다.<br>아래 링크를 클릭하여 로그인 해주시기 바랍니다.</p>
                    </div>
                    <div style="padding: 20px 30px; background: #f7f8f9;"><a style="font-size: 18px; font-weight: bold;" href="http://{{ domain }}{% url 'common:activate' uid64=uid token=token %}">인증하기</a></div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
{% endautoescape %}